[package]
name = "netecho-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.23"
http-body-util = "0.1"
hyper = { version = "1", features = ["http1", "server"] }
hyper-util = { version = "0.1", features = ["server", "tokio"] }
lazy_static = "1"
rand = { version = "0.10", features = ["thread_rng"] }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "signal"]}
