[package]
name = "netecho-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
http-body-util = "0.1"
hyper = { version = "1", features = ["http1", "server"] }
hyper-util = { version = "0.1", features = ["server", "tokio"] }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread"]}
